Models/Project.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BugTracker.Models
{
    public class Project
    {
        public int Id { get; set; }

        [DisplayName("Company")]
        public int? CompanyId { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Project Name")]
        public string Name { get; set; }

        [DisplayName("Description")]
        public string Description { get; set; }

        [DisplayName("Start Date")]
        [DataType(DataType.Date)]
        public DateTimeOffset StartDate { get; set; }

        [DisplayName("End Date")]
        [DataType(DataType.Date)]
        public DateTimeOffset EndDate { get; set; }

        [DisplayName("Priority")]
        public int? ProjectPriorityId { get; set; }

        [NotMapped]
        [DataType(DataType.Upload)]
        public IFormFile ImageFormFile { get; set; }

      
        [DisplayName("File Name")]
        public string ImageFileName { get; set; }

        public byte[] ImageFileData { get; set; }

        [DisplayName("File Extention")]
        public string ImageContentType { get; set; }

        [DisplayName("Archived")]
        public bool Archived { get; set; }


        // Navigation Properties
        public virtual Company Company { get; set; }
        public virtual ProjectPriority ProjectPriority { get; set; }
        public virtual ICollection<BugTrackerUser> Members { get; set; } = new HashSet<BugTrackerUser>();
        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();

    }
}

Models/ViewModels/AssignProjectManagerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTracker.Models.ViewModels
{
    public class AssignProjectManagerViewModel
    {
        public Project Project { get; set; }
        public SelectList ProjectManagerList { get; set; }
        public string ProjectManagerId { get; set; }
    } 
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BugTracker.Data;
using BugTracker.Models;
using Microsoft.AspNetCore.Identity;
using BugTracker.Extentions;
using BugTracker.Models.Enums;
using BugTracker.Services.Interfaces;
using System.ComponentModel.Design;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using BugTracker.Models.ViewModels;

namespace BugTracker.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly UserManager<BugTrackerUser> _userManager;
        private readonly IBugTrackerProjectService _projectService;
        private readonly IBugTrackerLookupService _lookupService;
        private readonly IBugTrackerTicketService _ticketService;
        private readonly IBugTrackerFileService _fileService;
        private readonly IBugTrackerHistoryService _historyService;

        public TicketsController(UserManager<BugTrackerUser> userManager, IBugTrackerProjectService projectService, IBugTrackerLookupService lookupService, IBugTrackerTicketService ticketService, IBugTrackerFileService fileService, IBugTrackerHistoryService historyService)
        {
            _userManager = userManager;
            _projectService = projectService;
            _lookupService = lookupService;
            _ticketService = ticketService;
            _fileService = fileService;
            _historyService = historyService;
        }


        public async Task<IActionResult> MyTickets()
        {
            BugTrackerUser bugTrackerUser = await _userManager.GetUserAsync(User);

            List<Ticket> tickets = await _ticketService.GetTicketsByUserIdAsync(bugTrackerUser.Id, bugTrackerUser.CompanyId);

            return View(tickets);
        }

        public async Task<IActionResult> AllTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> tickets = await _ticketService.GetAllTicketsByCompanyAsync(companyId);

            if (User.IsInRole(nameof(Roles.Developer)) || (User.IsInRole(nameof(Roles.Submitter))))
            {
                return View(tickets.Where(t => t.Archived == false));
            }
            else
            {
                return View(tickets);
            }

        }

        public async Task<IActionResult> ArchivedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;
            List<Ticket> tickets = await _ticketService.GetArchivedTicketsAsync(companyId);

            return View(tickets);
        }



        [Authorize(Roles = "Admin,ProjectManager")]
        public async Task<IActionResult> UnassignedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            string bugTrackerUserId = _userManager.GetUserId(User);

            List<Ticket> tickets = await _ticketService.GetUnassignedTicketsAsync(companyId);

            if (User.IsInRole(nameof(Roles.Admin)))
            {
                return View(tickets);
            }
            else
            {
                List<Ticket> projectManagerTickets = new();

                foreach (Ticket ticket in tickets)
                {
                    if (await _projectService.IsAssignedProjectMangerAsync(bugTrackerUserId, ticket.ProjectId))
                    {
                        projectManagerTickets.Add(ticket);
                    }
                }

                return View(projectManagerTickets);
            }


        }


        [Authorize(Roles = "Admin,ProjectManager")]
        [HttpGet]
        public async Task<IActionResult> AssignDeveloper(int id)
        {
            AssignDeveloperViewModel model = new();

            model.Ticket = await _ticketService.GetTicketByIdAsync(id);
            model.Developers = new SelectList(await _projectService.GetProjectMembersByRoleAsync(model.Ticket.ProjectId, nameof(Roles.Developer)),
                                                                 "Id", "FullName");

            return View(model);
        }

        [Authorize(Roles = "Admin,ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignDeveloper(AssignDeveloperViewModel model)
        {
            if (model.DeveloperId != null)
            {
                BugTrackerUser bugTrackerUser = await _userManager.GetUserAsync(User);

                // oldTicket
                Ticket oldTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);

                try
                {
                    await _ticketService.AssignTicketAsync(model.Ticket.Id, model.DeveloperId);
                }
                catch (Exception)
                {
                    throw;
                }

                // newTicket
                Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);

                await _historyService.AddHistoryAsync(oldTicket, newTicket, bugTrackerUser.Id);

                return RedirectToAction(nameof(Details), new { id = model.Ticket.Id });
            }

            return RedirectToAction(nameof(AssignDeveloper), new { id = model.Ticket.Id });
        }



        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }


            Ticket ticket = await _ticketService.GetTicketByIdAsync(id.Value);


            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public async Task<IActionResult> Create()
        {
            BugTrackerUser bugTrackerUser = await _userManager.GetUserAsync(User);

            int companyId = User.Identity.GetCompanyId().Value;

            if (User.IsInRole(nameof(Roles.Admin)))
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetAllProjectsByCompany(companyId), "Id", "Name");
            }
            else
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetUserProjectsAsync(bugTrackerUser.Id), "Id", "Name");
            }


            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ProjectId,TicketTypeId,TicketPriorityId")] Ticket ticket)
        {

            BugTrackerUser bugTrackerUser = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {

                try
                {
                    ticket.Created = DateTimeOffset.Now;
                    ticket.OwnerUserId = bugTrackerUser.Id;

                    ticket.TicketStatusId = (await _ticketService.LookupTicketStatusIdAsync(nameof(BugTrackerTicketStatus.New))).Value;

                    await _ticketService.AddNewTicketAsync(ticket);

                    Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(ticket.Id);
                    await _historyService.AddHistoryAsync(null, newTicket, bugTrackerUser.Id);

                    //TODO: Ticket Notification
                    return View(ticket);
                }
                catch (Exception)
                {
                    throw;
                }
            }


            if (User.IsInRole(nameof(Roles.Admin)))
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetAllProjectsByCompany(bugTrackerUser.CompanyId), "Id", "Name");
            }
            else
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetUserProjectsAsync(bugTrackerUser.Id), "Id", "Name");
            }


            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name");
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ticket ticket = await _ticketService.GetTicketByIdAsync(id.Value);

            if (ticket == null)
            {
                return NotFound();
            }

            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name", ticket.TicketPriorityId);
            ViewData["TicketStatusId"] = new SelectList(await _lookupService.GetTicketStatusesAsync(), "Id", "Name", ticket.TicketStatusId);
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name", ticket.TicketTypeId);

            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Created,Updated,Archived,ProjectId,TicketTypeId,TicketPriorityId,TicketStatusId,OwnerUserId,DeveloperUserId")] Ticket ticket)
        {

Views/Projects/AllProjects.cshtml
@model IEnumerable<BugTracker.Models.Project>
@using BugTracker.Models.Enums
@using Microsoft.AspNetCore.Identity
@using BugTracker.Services.Interfaces

@inject UserManager<BugTrackerUser> UserManager
@inject IBugTrackerProjectService ProjectService

@{
    ViewData["Title"] = "My Projects";
    BugTrackerUser bugTrackerUser = await UserManager.GetUserAsync(User);
}


@section VendorCSS {

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">

    <link rel="stylesheet" href="~/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
    <link rel="stylesheet" href="~/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
    <link rel="stylesheet" href="~/vendor/sweetalert/sweetalert.css" />

    <link rel="stylesheet" href="~/vendor/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css">
    <link rel="stylesheet" href="~/vendor/jvectormap/jquery-jvectormap-2.0.3.min.css" />
    <link rel="stylesheet" href="~/vendor/morrisjs/morris.min.css" />
    <link rel="stylesheet" href="~/vendor/nestable/jquery-nestable.css" />
    <link rel="stylesheet" href="~/vendor/chartist/css/chartist.min.css">
    <link rel="stylesheet" href="~/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css">

}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12">
        <div class="card">


            <div class="header">
                <h2>All Projects </h2>
                @if (User.IsInRole(nameof(Roles.Admin)) || User.IsInRole(nameof(Roles.ProjectManager)))
                {
                    <p>
                        <a asp-action="Create" class="btn btn-success mt-3">Create New Project</a>
                    </p>
                }
            </div>


            <div class="body">
                <div class="card-body p-0">
                    <div class="table-responsive mt-4">
                        <table id="ProjectsTable" class="table m-b-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">
                                        Project Name
                                    </th>

                                    <th scope="col">
                                        Project End Date
                                    </th>

                                    <th scope="col">
                                        Progress
                                    </th>
                                    <th scope="col">
                                        Status
                                    </th>
                                    <th scope="col">

                                    </th>


                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {



                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name) <hr>
                                            <span>Created On</span> @Html.DisplayFor(modelItem => item.StartDate)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.EndDate)
                                        </td>

                                        <td>
                                            <div class="progress progress-xs">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;"> <span class="sr-only">100% Complete</span> </div>
                                            </div>
                                        </td>


                                        <td>
                                            @Html.DisplayFor(modelItem => item.ProjectPriority.Name)
                                        </td>
                                        <td>

                                            <a class="btn btn-sm btn-outline-primary" asp-action="Details" asp-controller="Projects" asp-route-id="@item.Id"><i class="icon-eye" aria-hidden="true"></i></a>


                                            @{
                                                bool isProjectPM = (await ProjectService.GetProjectManagerAsync(item.Id))?.Id == bugTrackerUser.Id;
                                            }

                                            @if (User.IsInRole(nameof(Roles.Admin)) || isProjectPM)
                                            {

                                                <a class="btn btn-sm btn-outline-dark" asp-action="Edit" asp-controller="Projects" asp-route-id="@item.Id"><i class="icon-pencil" aria-hidden="true"></i></a>

                                                @if (item.Archived)
                                                {
                                                    <a asp-action="Restore" asp-route-id="@item.Id"><img src="~/images/logos/archivedDocument.png" style="width:32px;" height="30px;" /></a>
                                                }
                                                else
                                                {

                                                    <a asp-action="Archive" asp-route-id="@item.Id"><img src="~/images/logos/ActiveDocument.png" style="width:32px;" height="30px;" /></a>

                                                }
                                            }

                                        </td>

                                    </tr>
                                }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>








@section Scripts {



    <script src="~/bundles/chartist.bundle.js"></script>
    <script src="~/vendor/chartist/polar_area_chart.js"></script><!-- Polar Area Chart Js -->
    <script src="~/js/pages/charts/chartjs.js"></script>

    <script src="~/bundles/datatablescripts.bundle.js"></script>
    <script src="~/vendor/jquery-datatable/buttons/dataTables.buttons.min.js"></script>
    <script src="~/vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
    <script src="~/vendor/jquery-datatable/buttons/buttons.colVis.min.js"></script>
    <script src="~/vendor/jquery-datatable/buttons/buttons.html5.min.js"></script>
    <script src="~/vendor/jquery-datatable/buttons/buttons.print.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.min.js"></script> <!-- SweetAlert Plugin Js -->
    <script src="~/js/pages/tables/jquery-datatable.js"></script>

    @*  DASHBOARD JS CODE*@
    <script src="~/bundles/jvectormap.bundle.js"></script> <!-- JVectorMap Plugin Js -->
    <script src="~/bundles/morrisscripts.bundle.js"></script> <!-- Morris Plugin Js -->
    <script src="~/bundles/knob.bundle.js"></script> <!-- Jquery Knob-->
    <script src="~/vendor/nestable/jquery.nestable.js"></script> <!-- Jquery Nestable -->

    <script src="~/js/pages/ui/sortable-nestable.js"></script>
    <script src="~/js/index6.js"></script>


    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>


    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>


    <!-- *** Begin Chart JS Pie/Donut *** -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.0/dist/chart.min.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>

    <script>

        $(document).ready(function () {
            $('#ProjectsTable').DataTable();
        });


    </script>



}

Views/Projects/Archive.cshtml
@model BugTracker.Models.Project

@{
    ViewData["Title"] = "Archive";
}

<h1>Archive</h1>

<h3 class="font-weight-bold">Are you sure you want to Archive?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class = "col-sm-10">
           
                 @if (Model.ImageFileData != null)
                    {
                        <img class="img-fluid" style="width:120px; height:90px" src="data:image/*;base64,@(Convert.ToBase64String(Model.ImageFileData))">
                    }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageContentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageContentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Name)
        </dd class>
    </dl>
    
    <form asp-action="Archive">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Archive" class="btn btn-danger" /> |
        @*<a asp-action="Index">Back to List</a>*@
        <div>
    <a asp-action="Dashboard" asp-controller="Home">Back to Dashboard</a>
</div>
    </form>
</div>

Views/Projects/AssignMembers.cshtml
@model BugTracker.Models.ViewModels.ProjectMembersViewModel

<div class="container">
    <h2>Assign Members For</h2>
    <div class="row">

        <div class="col-6">
            <h3>@Model.Project.Name</h3>
        </div>
        <div class="card">
            <div class="card-header">
                <label asp-for="@Model.Users" class="form-control">Assign Team Members For Project</label>
            </div>
            <div class="card-body">
                <form method="post" asp-action="AssignMembers" asp-controller="Projects">
                    <input hidden asp-for="Project.Id" />
                    <div class="col-12 mb-4">
                        <div class="form-group">
                            <select required asp-for="@Model.SelectedUsers" class="form-control" asp-items="@Model.Users" multiple="multiple"></select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-4">
                            <input type="submit" class="btn btn-warning" value="Asssign Users" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div>
        <a asp-action="Details" asp-controller="Projects" asp-route-id="@Model.Project.Id">Back To Details</a>
    </div>

</div>

Views/Projects/AssignProjectManager.cshtml
@model BugTracker.Models.ViewModels.AssignProjectManagerViewModel

@{
    ViewData["Title"] = "Assign Project Manager";
}

<h1>@Model.Project.Name</h1>

<h4>Assign Project Manager</h4>
<hr />

<div class="row">
    <div class="col-4">
        <form method="post" asp-action="AssignProjectManager" asp-controller="Projects">
            <input hidden asp-for="Project.Id" />

            <p>@Model.Project.Name</p>

            <p>@Model.Project.Description</p>

            <div class="form-group">
                <label class="control-label">Select Project Manager</label>
                <select asp-for="ProjectManagerId" class="form-control" asp-items="@Model.ProjectManagerList">
                    <option></option>
                </select>

                <input type="submit" class="btn btn-primary" value="Assign" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="UnassignedProjects">Back To List</a>
</div>*@

<div>
    <a asp-action="Dashboard" asp-controller="Home">Back to Dashboard</a>
</div>

Views/Projects/Edit.cshtml
@model BugTracker.Models.ViewModels.AddProjectWithProjectManagerViewModel
@using BugTracker.Models.Enums
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Project.Id" />
            <input type="hidden" asp-for="Project.CompanyId" />
            <input type="hidden" asp-for="Project.ImageFileData" />
            <input type="hidden" asp-for="Project.ImageFileName" />
            <input type="hidden" asp-for="Project.ImageContentType" />


            <div class="form-group">
                <label asp-for="Project.Name" class="control-label"></label>
                <input asp-for="Project.Name" class="form-control" />
                <span asp-validation-for="Project.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Project.Description" class="control-label"></label>
                <input asp-for="Project.Description" class="form-control" />
                <span asp-validation-for="Project.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Project.StartDate" class="control-label"></label>
                <input asp-for="Project.StartDate" class="form-control" />
                <span asp-validation-for="Project.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Project.EndDate" class="control-label"></label>
                <input asp-for="Project.EndDate" class="form-control" />
                <span asp-validation-for="Project.EndDate" class="text-danger"></span>
            </div>

     

            <div class="form-group">
                <label class="control-label">Priority</label>
                <select asp-for="Project.ProjectPriorityId" class="form-control" asp-items="@Model.PriorityList">
                    <option>
                    </option>
                </select>
                <span asp-validation-for="Project.ProjectPriorityId" class="text-danger"></span>
            </div>

              <div class="form-group">
                <label class="control-label">Project Image</label>
                <input asp-for="Project.ImageFormFile" class="form-control" type="file" accept=".png, .jpg, .jpeg, .gif"
                       onchange="document.getElementById('imageFileData').src = window.URL.createObjectURL(this.files[0])" />
                <span asp-validation-for="Project.ImageFormFile" class="text-danger"></span>
            </div>

        
            <label class="control-label">Image Preview</label>

            @if (Model.Project?.ImageFileData != null)
            {
                <img id="imageFileData" class="img-fluid img-thumbnail" style="width:120px; height:90px" src="data:image/*;base64,@(Convert.ToBase64String(Model.Project.ImageFileData))">
            }
            else
            {
                <img id="imageFileData" class="img-fluid img-thumbnail" style="width:120px; height:90px">
            }

            @if (User.IsInRole(Roles.Admin.ToString()))
            {
                <div class="form-group">
                    <label class="control-label">Project Manager</label>
                    <select asp-for="ProjectManagerId" class="form-control" asp-items="@Model.ProjectManagerList">
                        <option>
                        </option>
                    </select>

                </div>
            }



            <div class="form-group" >
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Tickets" asp-action="AllTickets">Back to All Tickets</a>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }